-- EMERGENCY SCHEMA SYNC: Ensuring all columns in User.java exist in the database
ALTER TABLE users 
MODIFY COLUMN bio TEXT,
MODIFY COLUMN skills TEXT,
MODIFY COLUMN experience TEXT,
MODIFY COLUMN location TEXT;

-- Add Missing Social Media and System Fields
ALTER TABLE users
ADD COLUMN IF NOT EXISTS youtube TEXT,
ADD COLUMN IF NOT EXISTS tiktok TEXT,
ADD COLUMN IF NOT EXISTS twitter TEXT,
ADD COLUMN IF NOT EXISTS facebook TEXT,
ADD COLUMN IF NOT EXISTS threads TEXT,
ADD COLUMN IF NOT EXISTS instagram TEXT,
ADD COLUMN IF NOT EXISTS linkedin_profile TEXT,
ADD COLUMN IF NOT EXISTS behance TEXT,
ADD COLUMN IF NOT EXISTS vimeo TEXT,
ADD COLUMN IF NOT EXISTS personal_website TEXT,
ADD COLUMN IF NOT EXISTS phone TEXT,
ADD COLUMN IF NOT EXISTS projects_count TEXT;

-- Add Missing Notification and Permission Fields
ALTER TABLE users
ADD COLUMN IF NOT EXISTS contact_visible BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS email_notifications BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS follower_notifications BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS event_reminders BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS profile_visibility VARCHAR(50) DEFAULT 'Everyone',
ADD COLUMN IF NOT EXISTS message_permissions VARCHAR(50) DEFAULT 'Everyone';

-- Add Missing Auth Fields
ALTER TABLE users
ADD COLUMN IF NOT EXISTS auth_provider VARCHAR(50),
ADD COLUMN IF NOT EXISTS provider_id VARCHAR(255);

-- Add Missing Personal/Spec Fields
ALTER TABLE users
ADD COLUMN IF NOT EXISTS budget_quote TEXT,
ADD COLUMN IF NOT EXISTS available_from TEXT,
ADD COLUMN IF NOT EXISTS available_to TEXT,
ADD COLUMN IF NOT EXISTS gender TEXT,
ADD COLUMN IF NOT EXISTS age TEXT,
ADD COLUMN IF NOT EXISTS skin_tone TEXT,
ADD COLUMN IF NOT EXISTS height TEXT,
ADD COLUMN IF NOT EXISTS languages TEXT;

-- Re-verify all Craft-specific fields (in case any failed previously)
ALTER TABLE users
ADD COLUMN IF NOT EXISTS genres TEXT,
ADD COLUMN IF NOT EXISTS projects_directed TEXT,
ADD COLUMN IF NOT EXISTS budget_handled TEXT,
ADD COLUMN IF NOT EXISTS team_size_handled TEXT,
ADD COLUMN IF NOT EXISTS vision_statement TEXT,
ADD COLUMN IF NOT EXISTS editing_software TEXT,
ADD COLUMN IF NOT EXISTS editing_style TEXT,
ADD COLUMN IF NOT EXISTS portfolio_videos TEXT,
ADD COLUMN IF NOT EXISTS turnaround_time TEXT,
ADD COLUMN IF NOT EXISTS camera_expertise TEXT,
ADD COLUMN IF NOT EXISTS lighting_style TEXT,
ADD COLUMN IF NOT EXISTS daws TEXT,
ADD COLUMN IF NOT EXISTS sample_tracks TEXT,
ADD COLUMN IF NOT EXISTS instruments TEXT,
ADD COLUMN IF NOT EXISTS color_software TEXT,
ADD COLUMN IF NOT EXISTS color_panel TEXT,
ADD COLUMN IF NOT EXISTS color_monitor TEXT,
ADD COLUMN IF NOT EXISTS writer_genre TEXT,
ADD COLUMN IF NOT EXISTS writer_software TEXT,
ADD COLUMN IF NOT EXISTS writer_scripts TEXT,
ADD COLUMN IF NOT EXISTS vfx_software TEXT,
ADD COLUMN IF NOT EXISTS vfx_specialty TEXT;
