-- UPDATE_SCHEMA.sql
-- Run this to add missing columns to the users table

ALTER TABLE users ADD COLUMN IF NOT EXISTS instruments VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS daws VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS sample_tracks TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS color_software VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS color_panel VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS color_monitor VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS writer_genre VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS writer_software VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS writer_scripts TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS vfx_software VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS vfx_specialty VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS camera_expertise VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS lighting_style VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS editing_software VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS editing_style VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS portfolio_videos TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS turnaround_time VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS genres VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS projects_directed VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS budget_handled VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS team_size_handled VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS vision_statement TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS languages VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS availability VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS budget_quote VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS available_from DATETIME;
ALTER TABLE users ADD COLUMN IF NOT EXISTS available_to DATETIME;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS age VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS skin_tone VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS height VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS contact_visible BOOLEAN DEFAULT TRUE;
