-- SQL Script to update the users table with all craft-specific columns
-- Run this in your MySQL Workbench or Command Line if Hibernate auto-update is not working

USE crewcanvas_db;

-- 1. Basic Professional Details
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS skills VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS experience VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS languages VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS availability VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS contact_visible BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS projects_count VARCHAR(255);

-- 2. Social Links
ALTER TABLE users ADD COLUMN IF NOT EXISTS instagram VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS youtube VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS tiktok VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS twitter VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS vimeo VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS behance VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS facebook VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS threads VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS linkedin_profile VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS personal_website VARCHAR(255);

-- 3. Actor Specific Fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS height VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS weight VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS age_range VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS body_type VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS acting_experience TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS showreel_url VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS past_projects TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS portfolio_images LONGTEXT;

-- 4. Director Specific Fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS genres VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS projects_directed VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS budget_handled VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS team_size_handled VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS vision_statement TEXT;

-- 5. Editor Specific Fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS editing_software VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS editing_style VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS portfolio_videos VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS turnaround_time VARCHAR(255);

-- 6. DOP Specific Fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS camera_expertise VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS lighting_style VARCHAR(255);

-- 7. Music Director Specific Fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS daws VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS sample_tracks VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS instruments VARCHAR(255);

-- 8. Profile Images & Stats
ALTER TABLE users MODIFY COLUMN profile_picture LONGTEXT;
ALTER TABLE users MODIFY COLUMN cover_image LONGTEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS followers INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS following INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at DATETIME;
ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_provider VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS provider_id VARCHAR(255);

-- Success Message
SELECT 'Database update complete!' AS result;
